FROM postgres:15-alpine

# Set environment variables
ENV POSTGRES_DB=manifest_manager_db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expose PostgreSQL port
EXPOSE 5432

# Volume for data persistence
VOLUME ["/var/lib/postgresql/data"]
